In [1]:
import numpy as np

In [17]:
a = np.array([1,2,3], dtype='int16')
b = np.array([[2,3,4], [1,2,3]])
print(a)

[1 2 3]


In [9]:
# Get Dimension
b.ndim

2

In [10]:
# Get Shape: n by m Matrix
b.shape

(2, 3)

In [18]:
# Get Type 

a.dtype

dtype('int16')

In [20]:
# Get Size

a.itemsize

2

In [21]:
# Get a specific element [r,c]
b[1,2]

3

In [23]:
# Get a specific row
b[0,:]

array([2, 3, 4])

In [25]:
# Get a specific column
b[:,0]

array([2, 1])

# Initializing Different Types of Arrays

In [27]:
# All 0s matrix
zeroMatrix = np.zeros((3,3))
print(zeroMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
# All 1 Matrix
oneMatrix = np.ones((3,3,3), dtype='int16')
print(oneMatrix)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [29]:
# All other number Matrix
ontherNoMatrix = np.full((3,3), 6)
print(ontherNoMatrix)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [30]:
# Create Identity Matrix
indentityMatrix = np.identity(3)
print(indentityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Mathematics

In [31]:
c=np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [32]:
c-4

array([-3, -2, -1,  0])

# Linear Algebra

In [34]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [35]:
# find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

# I/O

genfromtxt
astype()