# Model Representation  (lecture2 and lecture3)

![title](img/ml_flow.png)

h: is model which can be linear or nonliner


## 1-Linear regression: 
  * one type of hypothesis function
  
## 2- Cost function:
  * used to measure the accuracy of our hypothesis function
  * one exampe is __Mean squared error__
      ![title](img/mse.png)
      
##  3- Gradient Descent:
  * summary as following: 
      ![title](img/sum_1.png)
  * Solution for find params to get min value is __Gradient Descent__
      ![title](img/gd_1.png)
  * := assignment means __a__ := __b__, give value of b to a
  * á: learn rate - step size following indicating direction
  
 

## 4- Matrices and vestor:
* rows * colums: 4 X 2 = 4 by 2 matrices
* A_ij: in A matrics, i_th row and j_th column
* Vector:  n by 1 matrix y_i - i_th element in vector

    ![title](img/mv_1.png)

In [13]:
import numpy as np

matrix_A = np.array([[1402, 191],[1371, 821], [949, 1437],[147,1448]])
print(matrix_A)

vecotr_y=np.array([[460], [232], [315], [178]])
print(vecotr_y.shape)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
(4, 1)


## 5 - Addition and Scalar Multiplication
    
 ![title](img/asm.png)

In [6]:
# Addition and subtraction
matrix_A = np.array([[1, 0],[2, 5], [3, 1]])
matrix_B = np.array([[4, 0.5],[2, 5], [0, 1]])
print(matrix_A+matrix_B)

# scalar mutiplication
print(matrix_A*3)

[[ 5.   0.5]
 [ 4.  10. ]
 [ 3.   2. ]]
[[ 3  0]
 [ 6 15]
 [ 9  3]]


## 6 - Matrix-Vector Multiplication

 ![title](img/mvm.png)

In [7]:
# matrix-vector Multiplication
matrix_A = np.array([[1, 3],[4, 0], [2, 1]])
matrix_B =np.array([[1],[5]])
print(matrix_A.dot(matrix_B))

[[16]
 [ 4]
 [ 7]]


## 7 - Matrix-Matrix Multiplication

 ![title](img/mmm.png)

In [8]:
# matrix-matrix Multiplication
matrix_A = np.array([[1, 3],[2, 5]])
matrix_B =np.array([[0, 1],[3, 2]])
print(matrix_A.dot(matrix_B))

[[ 9  7]
 [15 12]]


## 8 - Matrix Multiplication Properties

![title](img/mmp.png)

In [9]:
# Identity matrix

matrix_identity = np.identity(3)
print(matrix_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 9 - Inverse and Transpose

![title](img/it.png)

In [10]:
# Inverse matrix

b = np.array([[2,3],[4,5]])

inversed_b = np.linalg.inv(b)
print(inversed_b)

[[-2.5  1.5]
 [ 2.  -1. ]]


In [12]:
# Transpose 
b = np.array([[2,3],[4,5]])
transposed_b = b.transpose()
print(transposed_b)

[[2 4]
 [3 5]]
